### ISSUE TITLE
add turnofphrase javascript piece 

### ISSUE THREAD

**Issue by jxmorris12** [jmojmojmo/jmojmojmo.github.io#1]

**Comment by jmojmojmo** [comment]
Thanks for posting this piece; I'm sure it took some finagling. Can you please adjust the dimensions on both the homepage and the project page? See below. 

**Homepage and project page:**
1.  Please update the file to the newer one I sent you on I think 12/26. I can of course re-send you a dropbox link; I can post the additional SVG and updated .js file for the additional frame that the older version posted to the site is missing. 
2.  Please see if the initial animation frame can have its background color (#055470) in place at the start of the animation. Right now that first frame's background appears to be white, i.e. the  background color is appearing.

**Homepage:** 
1.  Please increase the fixed height of this 780 px width image to 350 pixels height. 

**Project page:**
1a.  I'm not sure if you intended this to be a scalable to browser width. Right now it doesn't appear to be scaling. (Note, it's totally fine if you can't get it to scale properly. While scalable would be preferable [to maximize the size and impact of the piece], what is more important is reliability and consistency of presentation.) 
1.b  IF you want to have it scalable to browser width, please make the ratio of width to height 2.25 to 1.0 (if that makes sense), and also please ensure that there are 50px at left and right of it. Right now it's looking like it is staying anchored to the left side of the browser, and leaving well over 50px to the right. 
2.  IF you choose to abandon scalable and opt for fixed pixel dimensions, then please make it 1400 px width  x  600 px height.

**Comment by jxmorris12** [comment]
1 updated js & svg
2 set background

1 increased fixed height (and fixed some margins)

1a now it should scale
2 set ratio
1.0 ensured margins
2 n/a
