### ISSUE TITLE
homepage grid arrangement problem

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#10]
I wasn't sure what to title this issue. There is one remaining problem with the grid arrangement, but more importantly, it shows me that I'm still not clear on how "col-width" and "img-col-width" values. 

Refer to my homepage mockup image I sent. Supplydemand piece is to be on same row as Evolution but it is currently appearing in the row about it. However, the "col-width" and "img-col-width" values for every post seems to be correct, from my understanding of how these variables work. 

Examples: Etc and Or pieces both have 2 and 1 for the values, which I think (as I understand it) correctly sets up a row consisting of 2 rather than 3 images, each image being one-column wide. But the Supplydemand piece is appearing on that row as well. Why? 

- - - 

Maybe the problem is that I'm not clear enough still on how to control the placement of each item with just these two variables. For instance since both the Etc and Or items have values of 2 and 1, that tells me that the row should be complete with just those two on a row (to match my mockup), and the next item should go on the next row; but that's not what's happening. 

At your house you explained it that col-width "describes the type of row" and img-col-width "describes how the item behaves in that row; what is around it." 

In your email you wrote that col-width is the number of columns that the entire piece takes up in a 3-column row, and that img-col-width is the actual width of the image.

...both explanations pretty much make sense to me but as I said above the homepage isn't in all cases acting accordingly so I'm still not clear. This is one that may be easiest to talk on phone...

**Comment by jxmorris12** [comment]
Yep, this is confusing -- I explained it correctly but it doesn't work as expected. I will get to work on this soon.

**Comment by jxmorris12** [comment]
Actually it was pretty easy! Sorry to have confused you with the image-col-width and col-width thing. That was very dumb on my part. Now it's just `col:1` or `col:2` based on the image width, and `classes: push-left` or `classes: push-right` to set an image margin and "push" the image or next image down a line. I'll explain more but that's basically how it works
