### ISSUE TITLE
Visual hover state for homepage images in desktop version

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#14]
This is I think my first full-on annoying request, because I've changed my mind from what I'd originally decided back in August (when I opted to have the cursor-turning-to-handpointer be the only visual cue for the clickable homepage images). 

I'm requesting that we implement a visual cue: Each image appears "lighter" on hover. This can be done with code, but I'm not sure exactly how. But since it is a common thing, I'm hoping I can help you research the best method for it and we can figure it out. 

When we discuss the method for accomplishing this, then we can discuss the degree of opacity for the white overlay (which I assume will be the  way to make the image appear lighter; say, a div of 50% opacity appears over the image on hover, that kinda thing).

**Comment by jxmorris12** [comment]
added 50% opacity, if you want to change the % it's in main.scss inside .home {} 

current line 38

**Comment by jmojmojmo** [comment]
Thanks, looking good, but I'm reopening the issue because I edited the CSS file on line 38 as you said (I lessened the .50 opacity to .20) but I'm not noticing the difference; the hover state looks unchanged. So I was wondering if I missed something.

**Comment by jxmorris12** [comment]
it worked actually (`opacity: .25`) but I think you might have meant `opacity: .75` so I changed it to that
