### ISSUE TITLE
Mobile site - navigation icons size and placement

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#15]
Please see attached PNG image which is a mobile screenshot, showing the existing size and positions of the SVG icons, as well as the desired (shown in pink) size and placement. 

By my estimation the SVG icons should be increased 140% from their current size.

![mobile_screenshots_compare](https://user-images.githubusercontent.com/31120702/36451550-652b17c6-165f-11e8-96bd-0fbf657292c9.png)

**Comment by jxmorris12** [comment]
I changed the padding around the navbar to be 20px and the icon size to 40px. let me know what you think of those sizes

**Comment by jxmorris12** [comment]
and the padding around each svg is also 20px

**Comment by jmojmojmo** [comment]
Thanks for the updates. The icon sizes are almost correct, and their positions are getting closer. 

Please see attached image "mobile_icons_issue.png" for reference. Once again the pink icons show intended size and position. 

The screenshot image shows the following things are needed: 
1. hamburger needs to be a bit larger (arrows and grid icons are correct size)
2. grid needs to move to the right
3. right arrow needs to move to the right
4. hamburger needs to move a bit to the left

![mobile_icons_issue](https://user-images.githubusercontent.com/31120702/36504097-5bfe2300-171d-11e8-908f-9b8b0ab9bad8.PNG)

**Comment by jmojmojmo** [comment]
Updating this issue with newer screenshot of the mobile site as it stands now, and also to address and clarify the anchored icons (and white band containing them). 

See the screenshots below; as with prior images attached to this issue, the pink is the intended placement of the mobile nav icons. 
"...a.png" shows the icon placement and intended height of the anchored white band.
"...b.png" shows what the homepage should look like when scrolled; note the nav icons in white band, as a persistent element atop the screen.

If this is something that we're just winging, and it's an ankle-biting trial&error thing, please just direct me to any and all the lines in the CSS where I can fool with it by putting in different padding values and stuff and I'll see if I can get the icons into the intended placement. It's obviously doable but I'm sure it isn't easy or obvious since neither of us have done much mobile before.     

![mobile_icons_issue_022418_a](https://user-images.githubusercontent.com/31120702/36626186-fa3afacc-18fb-11e8-97f0-63a737df9243.PNG)
![mobile_icons_issue_022418_b](https://user-images.githubusercontent.com/31120702/36626187-fa44be40-18fb-11e8-9230-d44f5bc749a6.png)

**Comment by jxmorris12** [comment]
hopefully better now

**Comment by jmojmojmo** [comment]
No more adjustments needed. Thank you for all the working with the size and positioning of these icons. 

Any further fiddling I will do on my end.

I'm re-opening to request that you let me know what particular lines in which files control these icons' sizes and placement. Then I'll be sure to save that info in my documentation and I'll know where to go if I want to attempt any other adjusting. Thanks.

**Comment by jxmorris12** [comment]
anything that references the variable `$nav-svg-size` really. it's kind of confusing - each width is set in two different places - but you should be able to change it pretty easily. all references are in `mobile.scss`

**Comment by jmojmojmo** [comment]
ok; thanks.
