### ISSUE TITLE
Mobile site - navigation icons appearance and behavior

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#16]
I'm opening this issue because as of now the SVG icons I provided for the mobile site's navigation are in place, but aren't functional. 

The icons' active state should be  #333333
The icons' inactive state should be #cccccc
(Note, the only icon that will have an inactive state is the grid icon, which will be inactive on the homepage, because that's what tapping that icon does; takes you back to the homepage grid.)
 

Please refer to the specs document "jmm_site_specs_movile.pdf" for all details regarding functionality, and for conditions determining the active or inactive state. In case you don't have or can't find the specs document I'm resending it by attaching to this issue. 

[jmm_site_specs_mobile.pdf](https://github.com/jmojmojmo/jmojmojmo.github.io/files/1742081/jmm_site_specs_mobile.pdf)

**Comment by jxmorris12** [comment]
good now
