### ISSUE TITLE
About page - implement body text hyperlink style to match elsewhere in site

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#17]
https://jmojmojmo.github.io/about

I probably should know how to do this myself at this point; but I'd like any links on the About page to not be default blue hyperlink color. 

Rather I'd like any links' active state to match what you did for the main navigation About link, and the "prev/next" links: the gray color for the link, and the black for the hover state.  (Note, just the active state color and the hover state color should be applied to this page; not any of the other styles from the navigation link.)

**Comment by jxmorris12** [comment]
fixed

**Comment by jmojmojmo** [comment]
Thanks but please no underlines since the other links' style in the site don't have underlines.

**Comment by jxmorris12** [comment]
fixed with the other link
