### ISSUE TITLE
About page - implement hyperlink to allow opening PDF in new browser tab

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#18]
https://jmojmojmo.github.io/about

Please make the words appearing in parentheses in the second paragraph "view UX design samples PDF" a link, which when clicked will open the attached PDF in a new browser tab.

[john_morris_worksamples.pdf](https://github.com/jmojmojmo/jmojmojmo.github.io/files/1742254/john_morris_worksamples.pdf)

**Comment by jxmorris12** [comment]
added

**Comment by jmojmojmo** [comment]
Thank you! However, note that in order to match the hyperlink style elsewhere in the site, it should be gray as you have it, but not underlined. Please remove the underlines for both the active state and hover state. Thanks.

**Comment by jxmorris12** [comment]
ok fixed. this class is in the CSS. mobile.scss class .link-default

the line I added to remove underlines is `text-decoration: none;`
