### ISSUE TITLE
Mobile site - first image on project page should be lower

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#19]
On mobile version, the first image on project pages are sitting too high on the screen, hence too claose to the navigation. 

See attached screenshots: Note the pink horizontal line, which is a good target point for the top of the first image on mobile version. 

Note, the project pages on mobile which have title and subhead copy above the image are ok, no changes needed. 

![img_6838](https://user-images.githubusercontent.com/31120702/36460667-679ea16c-1687-11e8-864a-f1eac795ce63.PNG)
![img_6839](https://user-images.githubusercontent.com/31120702/36460668-67a8a6f8-1687-11e8-8357-5335bd4e5eab.PNG)

**Comment by jxmorris12** [comment]
done

**Comment by jxmorris12** [comment]
added margin:100px
