### ISSUE TITLE
Mobile site - add cropped homepage images to mobile homepage grid

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#20]
I have uploaded the homepage images for mobile. 
They should appear in the same order as the desktop version. 

Some notes and questions:

-  All static images are 332 w X 222 h

-  I didn't resize the three gifs; I kept them 350px wide, on the assumption that they could be sized down by the code but I'm only guessing. It's not hard to re-generate new gifs at a smaller pixel size, so let me know if for consistency I should size these gifs to 332 x222 just like the static images. 
 
-  Not included is the "wantsneeds" javascript piece. Would you be able to add this to the mobile homepage and size it to match the other images? (It would have to be reduced in size so that the circle is only 222px tall.) (Not sure how best to do that...)

**Comment by jxmorris12** [comment]
looks good now
