### ISSUE TITLE
Mobile site - navigation icons must be anchored atop screen 

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#21]
On mobile devices, the navigation icons atop the screen are scrolling out of view, on both the homepage and on the project pages. 

The mobile navigation should be a persistent site element, locked in place. When you scroll down, the content should go "under" the mobile nav elements, so that the user can always navigate elsewhere even if they've scrolled down the page. 

Sorry if my UX specs document wasn't clear enough on this.

**Comment by jmojmojmo** [comment]
Again, this one is on me. I should have been much clearer about this. I see the nav is now anchored on mobile (thanks!), but it's important that the nav icons be contained in a white band which also is anchored, so that you can always see the icons. 

I'd be happy to provide more imagery but I think since an example exists, the best thing to do could be to refer again to the mobile version of this site, whose mobile nav icons are contained within an anchored white band: http://mikemcquade.com/

**Comment by jmojmojmo** [comment]
Attaching the same screenshot images that I attached to the mobile icons placement issue (see my comment just now in that issue), since they apply to this issue as well... 

![mobile_icons_issue_022418_a](https://user-images.githubusercontent.com/31120702/36626200-7f87e690-18fc-11e8-86ed-5a548afcbe04.PNG)
![mobile_icons_issue_022418_b](https://user-images.githubusercontent.com/31120702/36626201-7f91985c-18fc-11e8-83c0-386077c59321.png)

**Comment by jxmorris12** [comment]
OK should be better now -- the margins and the background too

**Comment by jmojmojmo** [comment]
This is really close now, thanks for the updates. 

The only request I'll make (and this is minor) is to make taller the white bar containing the nav icons. 

Please refer to the PNG I attached previously, with the pink line showing the desired height of the white bar. It's not far off now, but the hope is that there is as much white space below the icons as above the icons. Note, if updating this will only throw off the icon placements again, don't worry about it, I'll figure out how to fiddle with this stuff myself. 

As for the icons' placement I won't make any more comments as they're pretty much close enough, and I'll try any further tweaks from this point once I find out which lines in the CSS file control the padding and such.

**Comment by jxmorris12** [comment]
ok I added 20 px to the bottom hopefully that's better. no harm in closing/unclosing these

**Comment by jxmorris12** [comment]
feel free to be more specific about margins in terms of px, it's honestly easier than trying to guess from the picture

**Comment by jmojmojmo** [comment]
Thanks for adding the 20 px to the white band that the icons sit in; looks good. 

Since you mentioned pixel specificity for the mobile icons' placement, ok If you can do these two things that should be it. Let's try this:

-  Leave the left arrow in place 
-  Move the homepage grid icon 20 px to the right
-  Move the right arrow 40 px to the right

**Comment by jxmorris12** [comment]
ok done
