### ISSUE TITLE
wantsneeds mobile homepage image not appearing 

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#22]
I'm sure this problem is related to the layout type being javascript, rather than layout type being "post" 

I added the "m-thumbnail" of a static gif "wantsneeds_mobile_hp_332.gif but it's not appearing on the mobile homepage. So as I said I reckon it's because of the layout type and must require some sort of work-around. (Sorry.)

<img width="787" alt="screen shot 2018-02-22 at 4 49 23 pm" src="https://user-images.githubusercontent.com/31120702/36566113-855a5cae-17f0-11e8-851a-935ff52c0df8.png">

**Comment by jxmorris12** [comment]
yes you did it exactly right. i  changed something in `index.html` to show mobile images even for posts of `type: js`
