### ISSUE TITLE
turnofprase homepage image not appearing 

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#23]
Similar to the wantsneeds mobile homepage issue, this problem must be related to the layout type being javascript, rather than layout type being "post" 

I added the "m-thumbnail" of a static gif "turnofphrase_mobile_hp_332.gif but it's not appearing on the mobile homepage. So as I said I reckon it's because of the layout type and must require some sort of work-around.

**Comment by jxmorris12** [comment]
yes this is exactly right... just fixed it
