### ISSUE TITLE
Implement mobile menu - mockup attached 

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#24]
Please implement the hamburger menu as shown in the attached mockup "mobile_menu_expanded.png"

- I made the "X" icon SVG (I sent it via email) the same size as the hamburger icon so hopefully there won't be any weird shift in position when the menu is clicked, when it changes to the "X"
 
- Regardless of what page you're on on the mobile site, clicking the hamburger menu icon brings up this menu as shown in the mockup;  full white background.

- As you can see in the mockup I went ahead and made (for mobile only) the link "Work" so that it didn't look dumb when you clicked the menu icon and only saw the big word "About"  - so please just have the "Work" link send the user to the homepage. 

- The links "Work" and "About" are the same typeface (Nunito Sans) as the "About" link in the desktop site. I just have them black (not the link color gray used in the desktop site) because no hover state on mobile.

Let me know of any questions or if any of this is unclear? 

![mobile_menu_expanded](https://user-images.githubusercontent.com/31120702/36636782-4a2f9cf0-199b-11e8-9045-12b66b119060.png)

**Comment by jmojmojmo** [comment]
The mobile menu is looking good. The size and placement of the two links looks good. 

The only comments would be for the last bullet point I wrote (about font and color) when I created this issue: 

The links "Work" and "About" should be the same typeface (Nunito Sans) as the "About" link in the desktop site. And the words' color appears to be a purple right now, but it should be black.

**Comment by jxmorris12** [comment]
ok

**Comment by jmojmojmo** [comment]
This is a small nit, but also I'm hoping a small thing to fix (easy css change unless I'm missing something). 

As per the mockup, for the two mobile menu links, please center the type (rather than left-aligned as it is now). 

While I know the noticeable change will be small for now (because of just the two links), it will be good to get out of the way so that if and when I add additional menu items, the links will all be centered on the mobile device screen.

**Comment by jxmorris12** [comment]
just for reference: I removed spaces from around 'About' and added `text-align: center` to the `#link-box` (the bad name I gave thing that both of those links sit inside)
