### ISSUE TITLE
Mobile site - "About" page type should be larger on mobile

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#25]
Please see the attached current screenshot of the mobile version About page (which is just the desktop site, hence the type is way too small), and please also see my mockup showing desired type size for mobile version About page. 

**Please update the styling so that on mobile:**
-  the position of the About page body type is all the way to the left of the screen (not the 200 px left margin of the desktop site's About page)
-  the type is larger, as shown. (Can't guess at an actual number since I'm too ignorant of how you're implementing the styling. I assume using px sizes, not "em" but let me know if you'd like to discuss more specifically if my mockup is too much guesswork for you. 

(Also, not sure why this is happening, but on mobile the "Contact: morrisj..." is looking weird, like it's appearing twice, one on top of the other, slightly offset? If you don't see that on your end don't worry about it but that's how it's looking on my end.)

 
![mobile_about_current](https://user-images.githubusercontent.com/31120702/36707283-9be9aa3a-1b3b-11e8-90ff-405137fac14e.png)
![mobile_about_mockup](https://user-images.githubusercontent.com/31120702/36707284-9bf8144e-1b3b-11e8-940e-068b5bc6ec84.png)

**Comment by jxmorris12** [comment]
yes it's all px so font sizes are helpful

**Comment by jxmorris12** [comment]
let me know what you think now

**Comment by jmojmojmo** [comment]
Thanks for the update. The left margin starting point for the mobile About page body copy is good now. But the font is too small. 

Is this styling dealt with in lines 156-159 in the mobile css file?  There must be some other lines that I'm not seeing because I don't see font size. Anwyay if you identify the lines I should be looking at in that css file, I'll fool with the pixel values and test it so you don't have to deal with it. 

It's either that, or my overall direction would be: you can triple the size of the font on the mobile About page. (But if you let me know the lines where I could experiment, I'm happy to figure it out by trial and error).

**Comment by jxmorris12** [comment]
yep that's the right spot. add a line like `font-size: 30px;`
