### ISSUE TITLE
Allow Subhead text to appear on project pages even if Head text field is empty

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#27]
Don't know how hard this would be to pull off, but it would be very helpful if the site would allow me to include a project description (the smaller text) which you called the "subhead"  even if I don't enter anything for the "head" text. Is this doable? 

Right now when I've tried it the head and subhead text only appear if both fields are filled out.

If the above it too tricky or something, or if a half-ass solution is the best way to go for now, I'd be fine with say, entering an invisible character in the header that won’t show up on the site, just not sure if such an option exists; (just throwing it out there in case you're aware of something like this).

**Comment by jxmorris12** [comment]
very easy! fixed in https://github.com/jmojmojmo/jmojmojmo.github.io/commit/847b2941050a68c891591b5773fe7b7f99fb76d0
