### ISSUE TITLE
Add div for introductory sentence to homepage

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#28]
Please see attached mockups. 

Unlike prior mockups and specifications documents I haven't include pixel values or type sizes because I'm thinking/ hoping that you can add the element, as you have in other places (like "infobox" or whatever that was?), and direct me to all the lines in the code where I can work with the values for all margins around the div, and for the type size and linespacing, for both desktop and mobile. 

And, so you don't have to type in that dopey sentence, here is the type to copy and paste:
John Morris is a graphic artist, illustrator, and designer focused on creating intelligent and distinctive visual communications for publications, businesses, and organizations.

For the div placement: it should be centered, but not full-width; it should be narrower than the thumbnail grid as shown in the mockup. (And as I said I can adjust the space around it once I'm directed to the code for the margins, for both desktop and mobile.)

As for the type, it should be centered for both desktop and mobile versions. For font sizes, the desktop version should be the same type size as the About page type, and the mobile version should be the same type size as the mobile About page type. Which I guess means, it should inherit the already-done css for the type. 

![site_home_intro](https://user-images.githubusercontent.com/31120702/36878761-772b6fee-1d8e-11e8-9b6b-0bb116c6afc5.png)
![site_home_mobile_intro](https://user-images.githubusercontent.com/31120702/36878762-773b54ea-1d8e-11e8-9730-52071c5ef3b2.png)

**Comment by jxmorris12** [comment]
the font sizes are wrong but it should look OK now. CSS is in `main.scss` for desktop and `mobile.scss` for mobile -- look for `#main-description`
