### ISSUE TITLE
images not appearing on project pages with more than one image 

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#3]
See posts "amp" and "mullitover" 

For example, when I updated the "amp" post by removing images 2 and 3, leaving just the first image, then image then appeared on the site. When I put the other two images back in the code, the page goes back to no images showing. Who knows, I may be doing the comma-separated thing wrong...

**Comment by jxmorris12** [comment]
sorry! you actually have to write the lists of images in brackets, like [this.jpg, that.jpg]. they should all display now.
