### ISSUE TITLE
Project page - layout issues to be addressed

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#6]
In addition to the other open ticket about project page image sizing, there are these issues to address: 

1. images should appear vertically on this page; should never be next to each other. (Example; on this page the second image appears to the right of the primary image, not under it.  https://jmojmojmo.github.io/etc ) 

2. Refer to "jmm_site_specs_project.pdf"  – specs were for 50 px at left and right of any full-width images, and 90px vertical space below/ above all images

**Comment by jxmorris12** [comment]
I tackled both of these things earlier; should be good now
