### ISSUE TITLE
Homepage spacing: Please make consistent the space between items

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#7]
Right now the space separating some of the images on the homepage grid are uneven. 

Spacing between gifs and jpegs appears to be fine. Perhaps the problem is just the challenge of placing the javascipt animation pieces? The problems are with those items: 
1. Space to the right of "wantsneeds" animation is too small
2. Space above and below "turn of phrase" animation is too small 

Please refer to page 2 of "jmm_site_specs_home.pdf" for reference. It specifies 80px horizontal space between images, and 90px vertical space between image. (Buuut since you're in there, while you're there if it's just one thing to change, feel free to increase the vertical space from 90 to 95px. But don't bother if you need to change it in several spots in the CSS, no biggie)

**Comment by jxmorris12** [comment]
the wants_needs thing is a weird size because of the nature of that flash-to-js thing. I tried to do what I could but it is probably off by a few px -- hopefully that's ok. If not I can try to think of something else.

besides that, these things should be fixed -- lemme know

**Comment by jmojmojmo** [comment]
All looking great and squared away. Thanks.
