### ISSUE TITLE
Copyright line placement on project pages (sticky footer)

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#8]
(Refer to the bottom of page 1 of "jmm_site_specs_project.pdf" for copyright line placement specs.)

The copyright line should be anchored to the bottom of the browser page regardless of the height of the page's content. 

Its placement (and behavior - meaning no white space scrolls into view under it if you scroll down) is great on homepage and most project pages.

But right now on the project pages with content that is not filling the browser window's vertical space, the copyright line is floating up into the page content. 

Please check these project pages so that the copyright line is anchored to bottom and responds to scrolling the way it does correctly on all other pages:   
1.  wantsneeds
2.  turn of phrase 
3.  evolution  
4.  helmets
5.  hopes fears 
6.  wwjd

**Comment by jxmorris12** [comment]
https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/
