### ISSUE TITLE
Copyright line - activate year formula and mailto: link  

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#9]
1.  Year 
Please make the copyright year a formula, i.e., = current year, rather than hard-coded, so that it won’t have to be manually changed each year.
  
2.  Email
Please activate the email link mailto:morrisj68@gmail.com

**Comment by jxmorris12** [comment]
easy peasy

**Comment by jmojmojmo** [comment]
Unfortunately now on all the pages except the homepage, for some reason the year is not appearing after the copyright symbol.

**Comment by jxmorris12** [comment]
oh oops

**Comment by jxmorris12** [comment]
actually it's working for me -- you might need to do a shift-refresh

**Comment by jxmorris12** [comment]
but if not I can investigate further

**Comment by jmojmojmo** [comment]
Yep the year is showing up now. Thanks. Bytheway I only re-opened this issue because I'd done like 20 shift-refreshes here and there over the course of an hour and it didn't show so I thought something else might have been going on.
